In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

In [2]:
df = pd.read_csv('PlayTennis.csv')
df.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [3]:
df.isnull().sum()* 100 / len(df)

Outlook        0.0
Temperature    0.0
Humidity       0.0
Wind           0.0
Play Tennis    0.0
dtype: float64

In [4]:
df['Temperature'].unique()

<StringArray>
['Hot', 'Mild', 'Cool']
Length: 3, dtype: str

In [5]:
ordinal_encoder = OrdinalEncoder(
    categories=[['Cool', 'Mild', 'Hot']]
)

In [6]:
df['Temperature'] = ordinal_encoder.fit_transform(
    df[['Temperature']]
)

In [15]:
df.head()

,Temperature,Humidity,Wind,Play Tennis,Outlook_Overcast,Outlook_Rain,Outlook_Sunny,Wind_Freq,Humidity_Freq
0,2.0,High,1,0,0.0,0.0,1.0,0.571429,0.5
1,2.0,High,0,0,0.0,0.0,1.0,0.428571,0.5
2,2.0,High,1,1,1.0,0.0,0.0,0.571429,0.5
3,1.0,High,1,1,0.0,1.0,0.0,0.571429,0.5
4,0.0,Normal,1,1,0.0,1.0,0.0,0.571429,0.5

In [7]:
df['Wind'].unique()

<StringArray>
['Weak', 'Strong']
Length: 2, dtype: str

In [8]:
le_wind = LabelEncoder()
df['Wind'] = le_wind.fit_transform(df['Wind'])

In [9]:
print(df[['Wind']].head())

   Wind
0     1
1     0
2     1
3     1
4     1

In [16]:
df.head()

,Temperature,Humidity,Wind,Play Tennis,Outlook_Overcast,Outlook_Rain,Outlook_Sunny,Wind_Freq,Humidity_Freq
0,2.0,High,1,0,0.0,0.0,1.0,0.571429,0.5
1,2.0,High,0,0,0.0,0.0,1.0,0.428571,0.5
2,2.0,High,1,1,1.0,0.0,0.0,0.571429,0.5
3,1.0,High,1,1,0.0,1.0,0.0,0.571429,0.5
4,0.0,Normal,1,1,0.0,1.0,0.0,0.571429,0.5

In [10]:
encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[['Outlook']])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(['Outlook'])
)
df = df.drop('Outlook', axis=1).join(encoded_df)

In [11]:
df.head()

,Temperature,Humidity,Wind,Play Tennis,Outlook_Overcast,Outlook_Rain,Outlook_Sunny
0,2.0,High,1,No,0.0,0.0,1.0
1,2.0,High,0,No,0.0,0.0,1.0
2,2.0,High,1,Yes,1.0,0.0,0.0
3,1.0,High,1,Yes,0.0,1.0,0.0
4,0.0,Normal,1,Yes,0.0,1.0,0.0

In [12]:
for col in [ 'Wind', 'Humidity']:
    freq = df[col].value_counts(normalize=True)
    df[col + '_Freq'] = df[col].map(freq)

In [13]:
le_target = LabelEncoder()
df['Play Tennis'] = le_target.fit_transform(df['Play Tennis'])

In [14]:
df.head()

,Temperature,Humidity,Wind,Play Tennis,Outlook_Overcast,Outlook_Rain,Outlook_Sunny,Wind_Freq,Humidity_Freq
0,2.0,High,1,0,0.0,0.0,1.0,0.571429,0.5
1,2.0,High,0,0,0.0,0.0,1.0,0.428571,0.5
2,2.0,High,1,1,1.0,0.0,0.0,0.571429,0.5
3,1.0,High,1,1,0.0,1.0,0.0,0.571429,0.5
4,0.0,Normal,1,1,0.0,1.0,0.0,0.571429,0.5